import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MasterSidebar from "./components/MasterSidebar/MasterSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row m-0 p-0">
          <div className="w-64">
            <MasterSidebar />
          </div>
          <div className="flex-1">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
